/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Estoque;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadastrarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarEstoque
     */
    public CadastrarEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtQtdProd = new javax.swing.JTextField();
        txtPrecoProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaCadastro = new javax.swing.JTable();
        btnConsultarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCadastrar.setText("Cadastrar!");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(370, 300, 100, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 90, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Preço:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 90, 30);
        getContentPane().add(txtNomeProd);
        txtNomeProd.setBounds(130, 30, 250, 30);
        getContentPane().add(txtQtdProd);
        txtQtdProd.setBounds(130, 80, 250, 30);

        txtPrecoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecoProd);
        txtPrecoProd.setBounds(130, 130, 250, 30);

        tbConsultaCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tbConsultaCadastro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 452, 70);

        btnConsultarProd.setText("Consultar");
        btnConsultarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarProd);
        btnConsultarProd.setBounds(245, 300, 100, 30);

        setSize(new java.awt.Dimension(520, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(txtNomeProd.getText().isEmpty()== true)
        {
            JOptionPane.showMessageDialog(null,"Campo invalido!");
            return;
        }
            
        if(txtQtdProd.getText().isEmpty()== true)
        {
            JOptionPane.showMessageDialog(null,"Campo invalido!");
            return;
        }
        if(txtPrecoProd.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,"Campo invalido!");
            return;
        }
        if(txtPrecoProd.getText().isEmpty() == false)
        {
            try{
               double preco = Double.parseDouble(txtPrecoProd.getText());
                Connection conexao;
                PreparedStatement st;
                ResultSet rs;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
            st = conexao.prepareStatement ("INSERT INTO tb_estoque (nome_prod, qtd_prod, preco_prod) VALUES (?,?,?)");
            st.setString(1, txtNomeProd.getText());
            st.setInt(2, Integer.parseInt(txtQtdProd.getText()));
            st.setDouble(3, Double.parseDouble(txtPrecoProd.getText()));
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Cadastro Efetuado");
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
            //Busca o item na tabela do BD
            st = conexao.prepareStatement("SELECT * FROM tb_estoque WHERE nome_prod = ?;");
            st.setString(1, txtNomeProd.getText());
            rs = st.executeQuery();

                if (rs.next()) {
                    DefaultTableModel dtm = (DefaultTableModel) tbConsultaCadastro.getModel();
                    Object[] dados = {rs.getString("id_prod"), rs.getString("nome_prod"), 
                                rs.getString("qtd_prod"), rs.getString("preco_prod")};
                    dtm.addRow(dados);
                }
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Código invalido");
                return;
            }
            catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem o driver na biblioteca" + ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro no BD está incorreto" + ex);
        }
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdActionPerformed
        
        
        
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet rs;
        //Conexão com o BD
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://34.133.232.193/db_raphas", "root", "admin123");
            //Busca o item na tabela do BD
            st = conexao.prepareStatement("SELECT * FROM tb_estoque WHERE nome_prod = ?;");
            st.setString(1, txtNomeProd.getText());
            rs = st.executeQuery();
                if (rs.next()) {
                    DefaultTableModel dtm = (DefaultTableModel) tbConsultaCadastro.getModel();
                    Object[] dados = {rs.getString("id_prod"), rs.getString("nome_prod"), 
                                rs.getString("qtd_prod"), rs.getString("preco_prod")};
                    dtm.addRow(dados);
                }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Sem biblioteca instalada " + ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Parametro do banco errado " + ex);
        }
    }//GEN-LAST:event_btnConsultarProdActionPerformed

    private void txtPrecoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoProdActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultaCadastro;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPrecoProd;
    private javax.swing.JTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables
}
