/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        txtLogin.requestFocus();
        
        //Telas.MenuCadastro m;
        //m = new Telas.MenuCadastro();
        //if(m.isVisible() == true)
        //{
           //btnCadastrar.setEnabled(true);
        //}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnome = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        lblICONE = new javax.swing.JLabel();
        btnSair = new javax.swing.JToggleButton();
        btnLogin = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblnome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnome.setText("Login:");
        getContentPane().add(lblnome);
        lblnome.setBounds(20, 96, 50, 40);

        lblsenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsenha.setText("Senha:");
        getContentPane().add(lblsenha);
        lblsenha.setBounds(20, 146, 60, 40);

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(70, 100, 230, 30);

        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(pswSenha);
        pswSenha.setBounds(70, 152, 230, 30);

        lblICONE.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblICONE.setText("LOGIN");
        getContentPane().add(lblICONE);
        lblICONE.setBounds(150, 10, 60, 70);

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair.");
        btnSair.setBorder(null);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(240, 240, 90, 30);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(20, 240, 100, 30);

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(130, 240, 100, 30);

        setSize(new java.awt.Dimension(359, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            pswSenha.requestFocus();
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(txtLogin.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Campo invalido");
            return;
        }
        if(pswSenha.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Campo Invalido");
            return;
        }
        else
        {
            try {
            Connection conexao;
            PreparedStatement st;
            //Conexão com o BD
             ResultSet rs;
             String nome,cargo;
          
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
            //Busca o usuário na tabela do BD
            st = conexao.prepareStatement("SELECT * FROM tb_funcionarios where nome_func = ? and senha_func = ?");
            st.setString (1, txtLogin.getText());
            st.setString (2, pswSenha.getText());
            rs = st.executeQuery();
            if (rs.next()){
                
                Telas.MenuPrincipal tela;
                tela = new Telas.MenuPrincipal();
                JOptionPane.showMessageDialog(null, "Bem vindo " + rs.getString("nome_func") + "!!");
                
                Telas.MenuPrincipal a;
                a = new Telas.MenuPrincipal(rs.getString("nome_func"),rs.getString("cargo_func"));
                a.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos");
                return;
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
            return;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
            return;
        }
            
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Telas.MenuCadastro t;
        t = new Telas.MenuCadastro();
        t.setVisible(true);
        //btnCadastrar.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel lblICONE;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
