/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class MenuCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public MenuCadastro() {
        initComponents();
    }
    public MenuCadastro (String nome, String Cargo){
        //lblSaudacao.setText("Seja bem vindo " + nome + "!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmarsenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cargo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 270, 50, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 50, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 50, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 50, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("e-mail:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 50, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Cadastro");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 10, 80, 50);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(230, 320, 100, 30);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(350, 320, 100, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(120, 70, 270, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(120, 110, 270, 30);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(120, 190, 270, 30);

        txtEmail.setToolTipText("");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 230, 270, 30);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balconista", "Caixa", "Gerente", " " }));
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(120, 270, 170, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Confirmação:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 150, 100, 30);
        getContentPane().add(txtConfirmarsenha);
        txtConfirmarsenha.setBounds(120, 150, 270, 30);

        setSize(new java.awt.Dimension(485, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //Todas validações, e em seguida transferir para banco
        if(txtNome.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nome Invalido!");
            return;
        }
        if(txtSenha.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Senha Invalida!");
            return;
        }
        if(txtConfirmarsenha.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Senha Invalida!");
            return;
        }
        if(txtIdade.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Idade Invalido!");
            return;
        }
        if(txtEmail.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "E-mail Invalido!");
            return;
        }
        if(txtSenha.getText().equals(txtConfirmarsenha.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Senha Incorreta!");
            return;
        }
        if(Integer.parseInt(txtIdade.getText()) < 18)
        {
            JOptionPane.showMessageDialog(null,"Idade Invalida");
            return;
        }
        if(txtEmail.getText().contains("@")== false)
        {
            JOptionPane.showMessageDialog(null,"Email invalido");
            return;
        }
        if(txtEmail.getText().contains(".com")== false)
        {
            JOptionPane.showMessageDialog(null,"Email invalido");
            return;
        }
        else{
            DataBase.dbCadastrofunc db;
            db = new DataBase.dbCadastrofunc(txtNome.getText(),txtSenha.getText(),Integer.parseInt(txtIdade.getText()),
                                             txtEmail.getText(), cmbCargo.getSelectedItem().toString());
            dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false);
        Telas.Login a;
        a = new Telas.Login();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtConfirmarsenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
