/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class MenuPrincipal extends javax.swing.JFrame {

    
    
    public MenuPrincipal(String nome, String cargo) {
        initComponents();
        btnAlterarVendas.setVisible(false);
        if (cargo.contains("Gerente") || cargo.contains("gerente"))
        {
            btnAlterarVendas.setVisible(true);
        }
        else{
            btnAlterarVendas.setVisible(false);
        }
    }
    public MenuPrincipal()
    {
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pncontroleestoque = new javax.swing.JPanel();
        lblcontroleestoque = new javax.swing.JLabel();
        btnAlterarEstoque = new javax.swing.JButton();
        btnConsultarEstoque = new javax.swing.JButton();
        btnCadastroEstoque = new javax.swing.JButton();
        pnControlepedidos = new javax.swing.JPanel();
        lblControlepedidos = new javax.swing.JLabel();
        btnConsultarVendas = new javax.swing.JButton();
        btnFazerVenda = new javax.swing.JButton();
        btnAlterarVendas = new javax.swing.JButton();
        pnConfiguracoes = new javax.swing.JPanel();
        lblconfiguracoes = new javax.swing.JLabel();
        btnContato = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pncontroleestoque.setLayout(null);

        lblcontroleestoque.setBackground(new java.awt.Color(0, 0, 0));
        lblcontroleestoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontroleestoque.setText(" Controle de Estoque");
        pncontroleestoque.add(lblcontroleestoque);
        lblcontroleestoque.setBounds(0, 0, 140, 40);

        btnAlterarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alterar.png"))); // NOI18N
        btnAlterarEstoque.setBorder(null);
        btnAlterarEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarEstoqueActionPerformed(evt);
            }
        });
        pncontroleestoque.add(btnAlterarEstoque);
        btnAlterarEstoque.setBounds(30, 180, 60, 40);

        btnConsultarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LUPA.png"))); // NOI18N
        btnConsultarEstoque.setBorder(null);
        btnConsultarEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstoqueActionPerformed(evt);
            }
        });
        pncontroleestoque.add(btnConsultarEstoque);
        btnConsultarEstoque.setBounds(30, 50, 60, 40);

        btnCadastroEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CADASTRO.png"))); // NOI18N
        btnCadastroEstoque.setBorder(null);
        btnCadastroEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroEstoqueActionPerformed(evt);
            }
        });
        pncontroleestoque.add(btnCadastroEstoque);
        btnCadastroEstoque.setBounds(30, 110, 60, 40);

        getContentPane().add(pncontroleestoque);
        pncontroleestoque.setBounds(10, 0, 130, 390);

        pnControlepedidos.setLayout(null);

        lblControlepedidos.setBackground(new java.awt.Color(0, 0, 0));
        lblControlepedidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblControlepedidos.setText(" Controle de Vendas");
        pnControlepedidos.add(lblControlepedidos);
        lblControlepedidos.setBounds(0, 0, 140, 40);

        btnConsultarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/35.png"))); // NOI18N
        btnConsultarVendas.setBorder(null);
        btnConsultarVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendasActionPerformed(evt);
            }
        });
        pnControlepedidos.add(btnConsultarVendas);
        btnConsultarVendas.setBounds(30, 110, 60, 40);

        btnFazerVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vendas.png"))); // NOI18N
        btnFazerVenda.setBorder(null);
        btnFazerVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFazerVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerVendaActionPerformed(evt);
            }
        });
        pnControlepedidos.add(btnFazerVenda);
        btnFazerVenda.setBounds(30, 50, 60, 40);

        btnAlterarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alterar.png"))); // NOI18N
        btnAlterarVendas.setBorder(null);
        btnAlterarVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVendasActionPerformed(evt);
            }
        });
        pnControlepedidos.add(btnAlterarVendas);
        btnAlterarVendas.setBounds(30, 180, 60, 40);

        getContentPane().add(pnControlepedidos);
        pnControlepedidos.setBounds(190, 0, 130, 390);

        pnConfiguracoes.setLayout(null);

        lblconfiguracoes.setBackground(new java.awt.Color(0, 0, 0));
        lblconfiguracoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblconfiguracoes.setText(" Configurações");
        pnConfiguracoes.add(lblconfiguracoes);
        lblconfiguracoes.setBounds(0, 0, 110, 40);

        btnContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Contato.png"))); // NOI18N
        btnContato.setBorder(null);
        btnContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatoActionPerformed(evt);
            }
        });
        pnConfiguracoes.add(btnContato);
        btnContato.setBounds(20, 250, 60, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair logo.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnConfiguracoes.add(btnSair);
        btnSair.setBounds(20, 320, 60, 40);

        getContentPane().add(pnConfiguracoes);
        pnConfiguracoes.setBounds(370, 0, 100, 390);

        setSize(new java.awt.Dimension(530, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstoqueActionPerformed
        Telas.Estoque.ConsultarEstoque a= new Telas.Estoque.ConsultarEstoque();
        a.setVisible(true);
    }//GEN-LAST:event_btnConsultarEstoqueActionPerformed

    private void btnFazerVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerVendaActionPerformed
        Telas.Vendas.CadastroVendas a = new Telas.Vendas.CadastroVendas ();
        a.setVisible(true);
    }//GEN-LAST:event_btnFazerVendaActionPerformed

    private void btnConsultarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendasActionPerformed
        Telas.Vendas.ConsultaVendas a = new Telas.Vendas.ConsultaVendas();
        a.setVisible(true);
    }//GEN-LAST:event_btnConsultarVendasActionPerformed

    private void btnCadastroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroEstoqueActionPerformed
        Telas.Estoque.CadastrarEstoque a = new Telas.Estoque.CadastrarEstoque();
        a.setVisible(true);
    }//GEN-LAST:event_btnCadastroEstoqueActionPerformed

    private void btnAlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarEstoqueActionPerformed
        Telas.Estoque.AlterarEstoque a = new Telas.Estoque.AlterarEstoque();
        a.setVisible(true);
    }//GEN-LAST:event_btnAlterarEstoqueActionPerformed

    private void btnContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatoActionPerformed
        JOptionPane.showMessageDialog(null, "Contato: Email@gmail.com" +"\n"+"(11) 91234-1234");
    }//GEN-LAST:event_btnContatoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);  
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVendasActionPerformed
        Telas.Vendas.AlterarVenda a = new Telas.Vendas.AlterarVenda();
        a.setVisible(true);
    }//GEN-LAST:event_btnAlterarVendasActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarEstoque;
    private javax.swing.JButton btnAlterarVendas;
    private javax.swing.JButton btnCadastroEstoque;
    private javax.swing.JButton btnConsultarEstoque;
    private javax.swing.JButton btnConsultarVendas;
    private javax.swing.JButton btnContato;
    private javax.swing.JButton btnFazerVenda;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblControlepedidos;
    private javax.swing.JLabel lblconfiguracoes;
    private javax.swing.JLabel lblcontroleestoque;
    private javax.swing.JPanel pnConfiguracoes;
    private javax.swing.JPanel pnControlepedidos;
    private javax.swing.JPanel pncontroleestoque;
    // End of variables declaration//GEN-END:variables
}
