/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Vendas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AlterarVenda extends javax.swing.JFrame {

    /**
     * Creates new form AlterarVenda
     */
    public AlterarVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        jsConsulta = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodVend = new javax.swing.JTextField();
        txtNomecli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeVend = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProdutos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(520, 30, 90, 30);

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Produtos", "MeioPag", "Valor Total"
            }
        ));
        jsConsulta.setViewportView(tbConsulta);

        getContentPane().add(jsConsulta);
        jsConsulta.setBounds(20, 110, 590, 270);

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 30);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 30);

        txtCodVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodVendActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodVend);
        txtCodVend.setBounds(80, 12, 80, 30);

        txtNomecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomecliActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomecli);
        txtNomecli.setBounds(80, 60, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText(" Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 410, 70, 30);
        getContentPane().add(txtNomeVend);
        txtNomeVend.setBounds(100, 410, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Produtos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 480, 70, 30);
        getContentPane().add(txtProdutos);
        txtProdutos.setBounds(100, 480, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Valor :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 410, 70, 30);
        getContentPane().add(txtValor);
        txtValor.setBounds(340, 410, 210, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(390, 480, 90, 30);

        setSize(new java.awt.Dimension(681, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        String nomecli = txtNomecli.getText();
        String select = "*";

        Connection conexao;
        PreparedStatement st;
        ResultSet rs;
        //Conexão com o BD
        DefaultTableModel defTable;
        defTable = (DefaultTableModel) tbConsulta.getModel();
        defTable.setRowCount(0);

        if (nomecli.isEmpty() == true && txtCodVend.getText().isEmpty() == true) //txtNomeProd.setText("*");
        {
            try {

                Class.forName("com.mysql.jdbc.Driver");
                conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                //Busca o item na tabela do BD
                st = conexao.prepareStatement("SELECT * FROM tb_vendas;");
                rs = st.executeQuery();

                while (rs.next()) {

                    defTable = (DefaultTableModel) tbConsulta.getModel();
                    Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                        rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                        rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                    defTable.addRow(dados);

                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                return;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                return;
            }
        }
        if (txtCodVend.getText().isEmpty() == false) {
            try {

                int codigo = Integer.parseInt(txtCodVend.getText());

                if (codigo <= 0) {
                    JOptionPane.showMessageDialog(null, "Código Invalido");
                    return;
                } else {

                    try {

                        Class.forName("com.mysql.jdbc.Driver");
                        conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                        //Busca o item na tabela do BD
                        st = conexao.prepareStatement("SELECT * FROM tb_vendas Where ID_venda = ?;");
                        st.setInt(1, Integer.parseInt(txtCodVend.getText()));
                        rs = st.executeQuery();

                        while (rs.next()) {

                            defTable = (DefaultTableModel) tbConsulta.getModel();
                            Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                                rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                                rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                            defTable.addRow(dados);

                            txtNomeVend.setText(rs.getString("nome_vend"));
                            txtValor.setText(rs.getString("valortotal_vend"));
                            txtProdutos.setText(rs.getString("produtos_vend"));
                            txtCodVend.requestFocus();
                        }
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                        return;
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                        return;
                    }

                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Campo código invalido");
                return;
            }

            if (nomecli.isEmpty() == false) //txtNomeProd.setText("*");
            {
                try {

                    Class.forName("com.mysql.jdbc.Driver");
                    conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                    //Busca o item na tabela do BD
                    st = conexao.prepareStatement("SELECT * FROM tb_vendas Where  nome_vend = ?;");
                    st.setString(1, txtNomecli.getText());
                    rs = st.executeQuery();

                    while (rs.next()) {

                        defTable = (DefaultTableModel) tbConsulta.getModel();
                        Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                            rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                            rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                        defTable.addRow(dados);

                        txtNomeVend.setText(rs.getString("nome_vend"));
                        txtValor.setText(rs.getString("valortotal_vend"));
                        txtProdutos.setText(rs.getString("produtos_vend"));
                        txtCodVend.requestFocus();

                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                    return;
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                    return;
                }

            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtNomecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomecliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomecliActionPerformed

    private void txtCodVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodVendActionPerformed

        Connection conexao;
        PreparedStatement st;
        ResultSet rs;
        //Conexão com o BD
        DefaultTableModel defTable;
        defTable = (DefaultTableModel) tbConsulta.getModel();
        defTable.setRowCount(0);

        if (txtCodVend.getText().isEmpty() == false) {
            try {

                int codigo = Integer.parseInt(txtCodVend.getText());

                if (codigo <= 0) {
                    JOptionPane.showMessageDialog(null, "Código Invalido");
                    return;
                } else {

                    try {

                        Class.forName("com.mysql.jdbc.Driver");
                        conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                        //Busca o item na tabela do BD
                        st = conexao.prepareStatement("SELECT * FROM tb_vendas Where ID_venda = ?;");
                        st.setInt(1, Integer.parseInt(txtCodVend.getText()));
                        rs = st.executeQuery();

                        while (rs.next()) {

                            defTable = (DefaultTableModel) tbConsulta.getModel();
                            Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                                rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                                rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                            defTable.addRow(dados);

                            txtNomeVend.setText(rs.getString("nome_vend"));
                            txtValor.setText(rs.getString("valortotal_vend"));
                            txtProdutos.setText(rs.getString("produtos_vend"));
                            txtCodVend.requestFocus();
                        }
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                        return;
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                        return;
                    }

                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Campo código invalido");
                return;
            }
        }
    }//GEN-LAST:event_txtCodVendActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
            st = conexao.prepareStatement("UPDATE tb_Vendas SET nome_vend = ?, valortotal_vend  = ?, produtos_vend = ? WHERE id_venda = ?");
            st.setString(1, txtNomeVend.getText());
            st.setDouble(2, Double.parseDouble(txtValor.getText()));
            st.setString(3, txtProdutos.getText());
            st.setString(4, txtCodVend.getText());
            st.executeUpdate(); //Executa o comando SQL UPDATE

            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");

            txtCodVend.setText("");
            txtNomeVend.setText("");
            txtValor.setText("");
            txtProdutos.setText("");
            txtCodVend.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jsConsulta;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTextField txtCodVend;
    private javax.swing.JTextField txtNomeVend;
    private javax.swing.JTextField txtNomecli;
    private javax.swing.JTextField txtProdutos;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
