/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Vendas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eric
 */
public class ConsultaVendas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaVendas
     */
    public ConsultaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsConsulta = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodVend = new javax.swing.JTextField();
        txtNomecli = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Produtos", "MeioPag", "Valor Total"
            }
        ));
        jsConsulta.setViewportView(tbConsulta);

        getContentPane().add(jsConsulta);
        jsConsulta.setBounds(20, 110, 590, 270);

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 30);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 50, 30);
        getContentPane().add(txtCodVend);
        txtCodVend.setBounds(80, 12, 80, 30);

        txtNomecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomecliActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomecli);
        txtNomecli.setBounds(80, 60, 180, 30);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(505, 62, 90, 30);

        setSize(new java.awt.Dimension(661, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomecliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomecliActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        String nomecli = txtNomecli.getText();
        String select = "*";

        Connection conexao;
        PreparedStatement st;
        ResultSet rs;
        //Conexão com o BD
        DefaultTableModel defTable;
        defTable = (DefaultTableModel) tbConsulta.getModel();
        defTable.setRowCount(0);
        
        if (nomecli.isEmpty() == true && txtCodVend.getText().isEmpty() == true) //txtNomeProd.setText("*");
        {
            try {

                Class.forName("com.mysql.jdbc.Driver");
                conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                //Busca o item na tabela do BD
                st = conexao.prepareStatement("SELECT * FROM tb_vendas;");
                rs = st.executeQuery();

                while (rs.next()) {

                    defTable = (DefaultTableModel) tbConsulta.getModel();
                    Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                        rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                        rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                    defTable.addRow(dados);

                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                return;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                return;
            }
        }
        if (txtCodVend.getText().isEmpty() == false) {
            try {

                int codigo = Integer.parseInt(txtCodVend.getText());

                if (codigo < 1) {
                    JOptionPane.showMessageDialog(null, "Código Invalido");
                    return;
                } else {
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Campo código invalido");
                return;
            }

            if (nomecli.isEmpty() == false) //txtNomeProd.setText("*");
            {
                try {

                    Class.forName("com.mysql.jdbc.Driver");
                    conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                    //Busca o item na tabela do BD
                    st = conexao.prepareStatement("SELECT * FROM tb_vendas Where  nome_vend = ?;");
                    st.setString(1, txtNomecli.getText());
                    rs = st.executeQuery();

                    while (rs.next()) {

                    defTable = (DefaultTableModel) tbConsulta.getModel();
                    Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                        rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                        rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                    defTable.addRow(dados);

                }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                    return;
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                    return;
                }
                if (txtCodVend.getText().isEmpty() == false) {
                    try {

                        Class.forName("com.mysql.jdbc.Driver");
                        conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_raphas", "root", "admin123");
                        //Busca o item na tabela do BD
                        st = conexao.prepareStatement("SELECT * FROM tb_vendas Where ID_vend = ?;");
                        st.setString(1, txtCodVend.getText());
                        rs = st.executeQuery();

                        while (rs.next()) {

                    defTable = (DefaultTableModel) tbConsulta.getModel();
                    Object[] dados = {rs.getString("id_venda"), rs.getString("cpf_vend"),
                        rs.getString("nome_vend"), rs.getString("Produtos_vend"),
                        rs.getString("formapag_vend"), rs.getString("valortotal_vend")};
                    defTable.addRow(dados);

                }
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex);
                        return;
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto " + ex);
                        return;
                    }
                }
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jsConsulta;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTextField txtCodVend;
    private javax.swing.JTextField txtNomecli;
    // End of variables declaration//GEN-END:variables
}